### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Yoeri-Wysselinck** [hassio-addons/addon-sqlite-web#11]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Yoeri-Wysselinck** [comment]
Hi,

I'm getting an invalid config. It says that sqlite-web is not a valid option for panel iframe?

Invalid config for [panel_iframe]: [sqlite-web] is an invalid option for [panel_iframe]. Check: panel_iframe->panel_iframe->sqlite-web. (See /config/configuration.yaml, line 109). Please check the docs at https://home-assistant.io/components/panel_iframe/

**Comment by ludeeus** [comment]
You need to use `_` not `-`

**Comment by Yoeri-Wysselinck** [comment]
Thx mate, that did the trick indeed. Docs need to be corrected then as it states sqlite-web. 

> You need to use `_` not `-`
