### ISSUE TITLE
Support for access to other DBs, e.g. zigbee.db

### ISSUE THREAD

**Issue by nohat** [hassio-addons/addon-sqlite-web#143]
# Support for access to other DBs

It would be great if we could use this addon to look at other SQLite DBs, such as zigbee.db, used by ZHA.

## Expected behavior

I should be able to specify which file(s) I want to access using the application in the config

## Actual behavior

The filename is hardcoded in https://github.com/hassio-addons/addon-sqlite-web/blob/3dad89ede6627706819026e6377a0a44fa33c9e0/sqlite-web/rootfs/etc/services.d/sqlite-web/run#L10

## Proposed changes

It appears that this functionality used to exist but was removed in #114. I would propose to restore the ability to specify a filename, or at least provide a way to select from the *.db files in /config.

**Comment by frenck** [comment]
This feature has been removed in v3.0.0

**Comment by nohat** [comment]
Is there any reason the feature can't be restored?

**Comment by frenck** [comment]
It's not the goal of this add-on. The fact is was removed and didn't trigger a single response, shows the general use of it is almost 0. Thus not interested in adding it back.

**Comment by nohat** [comment]
> didn't trigger a single response, shows the general use of it is almost 0

The closure of this issue and this comment make me feel erased. I felt like my use case was being disrespected when I read it.

---

If I were to spend time working on (re-)creating this functionality, would it be better as a PR to this add-on or to create a new add-on that uses sqlite-web and supports opening other DB files?

One of the notes on the PR that removes it says "Removes configurable database paths (and thus access to the shares map)" which implies (to me) a security concern. I don't want to spend time working on adding functionality that would get rejected for security reasons, so please advise.

**Comment by frenck** [comment]
> I felt like my use case was being disrespected when I read it.

Its not disrespected, it is declined. Those are different things.
I'm not required to fulfill or maintain all uses cases out there. A sane, common and default setting is what makes things manageable, maintainable and understandable for the bigger audience.

This topic is closed.

**Comment by nohat** [comment]
Thank you for your reply. I appreciate understanding that it was not your intent to be disrespectful. 

I apologize for continuing to pester you with this as I understand you consider my use case to be of marginal utility. Can you clarify your position? Would you support any addon that allows viewing ZHA's `zigbee.db` SQLite DB or SQLite DBs generated and maintained by other HA integrations?

I'm sure no one would want to waste development effort creating a user friendly database selector for this addon if it won't be welcomed by the community, so I would appreciate your insight.

**Comment by frenck** [comment]
I'm not adding it. End of story.

Feel free to create your own.
