### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by bmaciag** [hassio-addons/addon-sqlite-web#194]
# Problem/Motivation

I installed the addon, but as soon as I click on content or execute a query I get a "502 Bad Gateway"
There is no hint in the log or the protocol. Any idea?

![image](https://user-images.githubusercontent.com/26123384/146751235-97fad3ee-6979-4a8d-a9f1-bbf64f950273.png)
![image](https://user-images.githubusercontent.com/26123384/146751249-20f8f6f0-ba52-4c2a-92fe-e449a8a22720.png)
![image](https://user-images.githubusercontent.com/26123384/146751263-21d9dc45-ff24-4f91-9165-3e3d9cb88549.png)

**Comment by 642040** [comment]
Same issue here...

**Comment by edudele** [comment]
mismo problema

**Comment by sinclairpaul** [comment]
SQLite uses a single file for the database, a 1.4Gb file means it needs to be loaded into memory for queries to execute.

If you are looking to retain that much data, and run queries against it, I would suggest a different database platform.

**Comment by edudele** [comment]
I think we all want to use this plugin to edit the homme assistant database for a little more and if it doesn't work then we'll go to another alternative.

**Comment by edudele** [comment]
I think we all want to use this plugin to edit the homme assistant database for a little more and if it doesn't work then we'll go to another alternative.

**Comment by 642040** [comment]
I was thinking the same, but my DB is only 22.3 MB and it is doing the same thing.

FYI:  It took me half a day to figure out how to get there, but sqlite3 from command line works perfectly and almost instantaneously.

**Comment by sinclairpaul** [comment]
@642040 Then I doubt your issue is the same, please post addon logs ideally in a new issue.

**Comment by 642040** [comment]
There is really not much there in the logs.  Attached is the whole session selecting the events table, then Content (exactly the same steps and result as @bmaciag).
[sqlite-web.log](https://github.com/hassio-addons/addon-sqlite-web/files/7771959/sqlite-web.log)

**Comment by sinclairpaul** [comment]
Please post the full addon log from startup, so we can see the version and platform

**Comment by 642040** [comment]
@sinclairpaul Sorry, it even says that right in the log :)
[sqlite-web.log](https://github.com/hassio-addons/addon-sqlite-web/files/7771997/sqlite-web.log)
