### ISSUE TITLE
Add possibility to browse for other databases

### ISSUE THREAD

**Issue by X1pheR** [hassio-addons/addon-sqlite-web#195]
# Problem/Motivation

This addon is great. I don't know if you accept feature requests but it would be great if you could also browse for other databases to open. Some other addons generate/use sqlite databases that I would love to open as well, like ZHA or Paperless NG.

## Expected behavior

N/A

## Actual behavior

N/A

## Steps to reproduce

N/A

## Proposed changes

To open the sqlite database of HA by default (if it exists). And make a browse button so that you can browse the folder structure to look for other databases to open.

**Comment by patrickcollins12** [comment]
I agree. I have a zigbee2mqtt database file I would love to be able to browse.

**Comment by yashijoe** [comment]
Yes it would be nice
At least to open the default database but not in config directory
Thanks

**Comment by frenck** [comment]
This option was removed in:

https://github.com/hassio-addons/addon-sqlite-web/releases/tag/v3.0.0
