### ISSUE TITLE
CSV-import failed

### ISSUE THREAD

**Issue by meinkama** [hassio-addons/addon-sqlite-web#198]
# Problem/Motivation

Import of CSV-file failed with message "404: not found"

## Expected behavior

CSV-file imported to database

## Actual behavior

File was not imported

## Steps to reproduce

Try importing a CSV-file

## Proposed changes

-

**Comment by loeffelpan** [comment]
Doesn't work for me.
I don't get error 404 but just a black screen.

**Comment by ZeroInputCtrl** [comment]
This seems to also be the case for JSON import as well. 404 not found. Doesn't appear to be a proxy issue as i've tried both my external url and internal route with the same issue.
