### ISSUE TITLE
Database not found (in custom location)

### ISSUE THREAD

**Issue by AdmiralStipe** [hassio-addons/addon-sqlite-web#212]
# Problem/Motivation

Database is located in media folder (to exclude it from backup), but the addon does not find it despite enabled option 
`database: "/media/home-assistant_v2.db"`. 
As a consequence, the addon doesn't start.  

Log file:
-----------------------------------------------------------
 Add-on: SQLite Web
 Explore your SQLite database
-----------------------------------------------------------
 Add-on version: 3.5.0
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 11 (bullseye)  (armv7 / raspberrypi4)
 Home Assistant Core: 2022.6.4
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/sqlite-web.sh
[13:31:44] FATAL: The database file '/media/home-assistant_v2.db' is not found
cont-init: info: /etc/cont-init.d/sqlite-web.sh exited 1
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by frenck** [comment]
The add-on cannot access other folders.
I think it can make sense to add the `share` folder, so the add-on can access that.

However, the `media` folder should not be used for this :)

**Comment by AdmiralStipe** [comment]
Oh, I see... well, the problem is, that "share" is still included in backup. I moved the database to "media" solely from the reason, that it's not included :). 
Any suggestions on which folder could be used additionally (and that it's not included in backup)?

**Comment by frenck** [comment]
Any folder can be excluded from backup, including "share":

![image](https://user-images.githubusercontent.com/195327/172842000-2f5571e1-45ca-4466-b6a1-2c9ca41553dd.png)

**Comment by AdmiralStipe** [comment]
Oh, silly me... Going that route, thx :)
