### ISSUE TITLE
Database location non-standard: Addon does not start

### ISSUE THREAD

**Issue by EarlOfBurton** [hassio-addons/addon-sqlite-web#215]
# Problem/Motivation
The database file is stored at a different location than  '/config/home-assistant_v2.db'. Thus the addon is not starting.
When I try to adjust the path via the 'Configuration' pane, I see the text: 'This add-on does not expose configuration for you to mess with…'
The documentation says, there should be a parameter 'Option: Database' to be set in the Configuration

## Expected behavior
Using the addon.

## Actual behavior
Addon does not start.

## Steps to reproduce
Having the database file at a different location than usual.

## Log
```
6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: SQLite Web
 Explore your SQLite database
-----------------------------------------------------------
 Add-on version: 3.6.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.7.5
 Home Assistant Supervisor: 2022.07.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/sqlite-web.sh
[11:56:49] FATAL: The database file '/config/home-assistant_v2.db' is not found
cont-init: info: /etc/cont-init.d/sqlite-web.sh exited 1
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by frenck** [comment]
The database file to use can be adjusted using a configuration option (see also the add-on documentation):

<https://github.com/hassio-addons/addon-sqlite-web/blob/main/sqlite-web/DOCS.md#configuration>

> When I try to adjust the path via the 'Configuration' pane, I see the text: 'This add-on does not expose configuration for you to mess with…'

That is a bug on the Home Assistant end, there is not much I can do about that from an add-on perspective.

**Comment by EarlOfBurton** [comment]
> The database file to use can be adjusted using a configuration option (see also the add-on documentation):

Sorry, I don't understand that... When I try to go to the 'Configuration'-Tab inside the Addon I get 'This add-on does not expose configuration for you to mess with…'.

Where do I need to set the database path otherwise?
Seems like I'm missing something.

Thanks for your help.
