### ISSUE TITLE
Importing CSV-file results in 404: not found

### ISSUE THREAD

**Issue by miljaar** [hassio-addons/addon-sqlite-web#220]
# Problem/Motivation

Importing any CSV-file is failing. I can select the file to import but when I press the button 'Import' it results in the error '404: not found'. There are no error messages visible in the sqlite web logfile showing the root cause of this message. I tried with Firefox and Chrome but both are giving the same result.
I'm running Home assistant on Ubuntu with Virtualbox:
Home Assistant 2022.10.2 
Supervisor 2022.10.0 
Operating System 9.0 
Frontend 20221006.0 - latest 

## Expected behavior

 I expect that the data in the CSV file is imported in the DB. Or at least that a clue of the root cause is given.

## Actual behavior

'404:not found' error is shown

## Steps to reproduce

* Open SQlite Web app
* select a table in the DB
* click 'Import'
* select CSV file to import via button 'Browse'
* filename is shown right next to button 'Browse'
* click button 'Import'

**Comment by sinclairpaul** [comment]
What's the file size you are uploading?

**Comment by miljaar** [comment]
I tried it with a file of +-20Mb and with a file of 3kB. Both result in the same error.

**Comment by sinclairpaul** [comment]
Looks like the redirect on the import pushes to an explicit path, i.e. /events/import/

**Comment by sinclairpaul** [comment]
Just to follow up on this, I don't believe this can be easily fixed under ingress (events is the table name and we would need to match on that, along with the others).

@frenck - your thoughts, I'm not sure we should even encourage the import of data to the HA database anyway.

**Comment by miljaar** [comment]
The import of data into the database is very useful in case the DB of HA gets corrupted and the user wants to keep/restore the history data of the old so called corrupt DB. I'm in this position and that import function looks for me the best and easiest way. As HA seems in some cases corrupts the DB this seems the only nice/proper way to keep the historical data that I find important.

**Comment by foxthefox** [comment]
same behaviour when importing JSON file (only 3 datasets), it would be very appreciated if the import function would work

**Comment by miljaar** [comment]
It's a pity that this issue hasn't been picked up.
