### ISSUE TITLE
Create Table not working in Web Interface

### ISSUE THREAD

**Issue by m053m716** [hassio-addons/addon-sqlite-web#223]
# Problem/Motivation

> I'm getting "Error: 404 not found" when I click the `Create` button (regardless of what I input the name as in the adjacent text entry field). I believe this may be related to issue #220 but I wanted to avoid tagging it onto that thread in case they are unrelated.

## Expected behavior

> A new table is created.

## Actual behavior

> No new table and Error: 404 not found.

## Steps to reproduce

> Input a new table name and click `Create` in the web interface of SQLite Web addon for Home-Assistant IO. My setup uses Raspberry Pi v4b that runs the Home-Assistant Operating System.

## Proposed changes

> I am open to suggestions if there's something I'm doing wrong here!

**Comment by repka3** [comment]
Same problem here. just go to 404
