### ISSUE TITLE
Log of SQL executed? Lost my whole stats DB

### ISSUE THREAD

**Issue by camsaway** [hassio-addons/addon-sqlite-web#224]
# Problem/Motivation

Have lost all data in all my stats tables. I'm sure I didn't use bad SQL but would like to check. I think some sort of clash happened and the DB got reset. (One table I would understand, but all the stats tables got wiped at the same time). Perhaps some sort of lock/sharing issue?

## Expected behavior

> Be able to view a log of all SQL commands executed through SQLite

## Actual behavior

> I've lost all my data and can't see why

## Steps to reproduce

>Not sure

## Proposed changes

* Add a log file of all SQL executed
* Add a warning for any SQL that will affect a large number of rows.

**Comment by camsaway** [comment]
Hi,
I still see this as a valid feature request that I would like to see in the add-on. How do I get it considered?

**Comment by frenck** [comment]
I don't understand the feature request or what you want, to be honest?
What can I do for you from an add-on perspective?

**Comment by camsaway** [comment]
Hi @frenck - thanks for the quick response. I was hoping the add-on could include a log/audit of SQL statements that are executed through it. Also, potentially a warning if more than say 1000 rows will be affected by an UPDATE/DELETE type query.

**Comment by frenck** [comment]
The add-on can't do that. Add-on wrap existing software, in this case SQLite Web. If you have feature requests for SQLite web itself, please do so with the upstream project.

When they release a new version, the  add-on will  ship an updated version.

Anyways, Happy New Year 🥂!

../Frenck
