### ISSUE TITLE
Fields data and hour is NULL

### ISSUE THREAD

**Issue by beatrizsilva1999** [hassio-addons/addon-sqlite-web#238]
# Problem/Motivation

> Previous behavior of "last_changed" and "last_updated" fields
Previously, the fields "last_changed" and "last_updated" used to be returned with a date and time stamp. However, now these fields only return a null value.

## Expected behavior

> Expected behavior of date and time fields
It was expected that the date and time fields would return normal values.

## Actual behavior

>Current behavior of storing null values Currently, the system is only storing the field values as null.

## Steps to reproduce

>Retrieving states from the database To retrieve states, we only need to access the database and request them. We observe that various fields that were previously filled are now null.

## Proposed changes

Uncertain cause of issue
It is currently unclear what caused this issue. Previously, the system was working normally, and as of the beginning of January, it was still functioning properly.

**Comment by frenck** [comment]
This is not an add-on issue, you are describing the contents of the Home Assistant database. That data structure is changing. 

../Frenck
