### ISSUE TITLE
Entity_id in HA States query All Null

### ISSUE THREAD

**Issue by AndyBowden** [hassio-addons/addon-sqlite-web#242]
Over last couple of days SQLite Addon queries on states is giving all results with entity_id as NULL.

I believe a recent HA update or a SQLite one may be the cause? It had worked fine for me until now.

**Comment by sammyke007** [comment]
+1

**Comment by frenck** [comment]
The database format of HA changed, this is not an add-on issue.

For the latest information on the database structure of HA, check out the data portal of Home Assistant here:

<https://data.home-assistant.io>

../Frenck

**Comment by AndyBowden** [comment]
I found the cause of this problem, as advised Frenck, was a new HA data structure. I overcame it easily by using the mapping between metadata_id and entity_id to be found in the table states_meta.
