### ISSUE TITLE
Addon not starting

### ISSUE THREAD

**Issue by augi** [hassio-addons/addon-sqlite-web#267]
# Problem/Motivation

I have the same observation as #255 and #256. I'm running the latest version of HA (on Intel NUC) and the latest version of this plugin.

## Expected behavior

If I click "Start" button, then the addon starts.

## Actual behavior and Steps to reproduce

If I click "Start" then the wheel is rotating indefinitely. If I refresh the page, the "Start" button is shown again (without the wheel, so I can click it again).

If I allow showing the link in Sidebar, it always tells me that the addon is not running. When I click "Start", the wheel rotates indefinitely again.

I tried several restarts, and the behavior is still the same.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: SQLite Web
 Explore your SQLite database
-----------------------------------------------------------
 Add-on version: 3.9.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.8.3
 Home Assistant Supervisor: 2023.08.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-sqlite-web: starting
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-sqlite-web successfully started
s6-rc: info: service sqlite-web: starting
s6-rc: info: service sqlite-web successfully started
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[12:15:29] INFO: Starting SQLite Web...
s6-rc: info: service legacy-services successfully started
 * Serving Flask app 'sqlite_web.sqlite_web'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8080
Press CTRL+C to quit
[12:15:29] INFO: Starting NGINX...
```

## Proposed changes

I don't know how to fix it. Maybe the problem could be that the server is started on a port that is already used.

**Comment by frenck** [comment]
This is not an add-on issue, same solution as in https://github.com/hassio-addons/addon-sqlite-web/issues/255 and https://github.com/hassio-addons/addon-sqlite-web/issues/256; restart your machine. Home Assistant lost track of the add-on.

../Frenck

**Comment by augi** [comment]
Did it, didn't help 😢 Do you have any idea why it is happening to this addon and not the others, please? 🙏
