### ISSUE TITLE
Error 404 when importing data

### ISSUE THREAD

**Issue by nagyrobi** [hassio-addons/addon-sqlite-web#269]
# Problem/Motivation

When trying to import data from a CSV or JSON file, an error 404 appears. UI dies, have to reload the entire ingress session.

## Expected behavior

After file upload, show the correct message.

## Actual behavior

After file upload, the UI jumps to an inexistent location.

## Steps to reproduce

Exported data in csv format, to make adjustments. When trying to import it back (drop before, etc.), by selecting a CSV file through the browser, an error 404 appears after the file has been uploaded. The data is actually being imported, as after re-loading the addon UI, a successfull message is seen, and the data is present as expected.

## Proposed changes

See also https://github.com/hassio-addons/addon-sqlite-web/issues/233

**Comment by sinclairpaul** [comment]
Can you confirm the table name you are importing to and from, it would also be helpful to get the output from the Browser dev console for the full path that the 404 is generated from.

**Comment by nagyrobi** [comment]
I suggest to do these steps on an experimental, test instance of HA.
The error appears in various forms. Looks like the ingress URL is not correct.

You can try with the `statistics` table. 
1. Export it to CSV format, save the file on your computer.
2. Drop it (browser works at http://HA.IP:8123/api/hassio_ingress/5I1Mp6pl7b-QrFakM60Mbqu_vw0cyE_jpCkbtUy6XTw/statistics/drop/ and then it will jump to http://HA.IP:8123/) > entire HA instance wiil re-appear duplicated in the window.
3. Click on the left on some other HA menu, eg. Media or DevTools, then click again on SQLite to re-load its ingress. 
You'll see _table "statistics" dropped successfully_
4. In the top right, click on create new table `statistics` -> 404 not found message. (browser tries to jump to http://HA.IP:8123/create-table/ subdocument, status will be 404)
5. Click on the left on some other HA menu, eg. DevTools, then click again on SQLite to re-load its ingress.
You'll see that the table was not created!!! 
6. However, you can of course create it manually by running this query in any table's Query window:
```sql
CREATE TABLE statistics  (
  id INTEGER NOT NULL,
  created DATETIME,
  start DATETIME,
  mean FLOAT,
  min FLOAT,
  max FLOAT,
  last_reset DATETIME,
  state FLOAT,
  sum FLOAT,
  metadata_id INTEGER,
  created_ts FLOAT,
  start_ts FLOAT,
  last_reset_ts FLOAT,
  PRIMARY KEY (id),
  FOREIGN KEY(metadata_id) REFERENCES statistics_meta (id) ON DELETE CASCADE
)
```
7. Click on the new `statistics` table > Content (which is empty), click Import and browse for the file previously exported. Click on Import button.
Depending on your file size, this might take some time. (browser works at http://HA.IP:8123/api/hassio_ingress/5I1Mp6pl7b-QrFakM60Mbqu_vw0cyE_jpCkbtUy6XTw/statistics/import/)
After import fininshes, a 404 page appears again (at location http://HA.IP:8123/statistics/content/)
8. Click on the left on some other HA menu, eg. DevTools, then click again on SQLite to re-load its ingress.
You'll see message like _Successfully imported 119190 objects from statistics-export.csv._
Click on the `statistics` table > Content, uploaded data is there.

**Comment by sinclairpaul** [comment]
The issue is to do with how the application functions (which expects to be served on root) and how ingress functions (which runs as a sub folder).

In order to get the redirects to work, we have to re-write for example at:

https://github.com/hassio-addons/addon-sqlite-web/blob/9c38342f647e0106525c889fd02fc6300e4322fc/sqlite-web/rootfs/etc/nginx/templates/ingress.gtpl#L22C9-L22C62

We won't be able to fix the redirect under the drop, as you can't easily re-write root requests, I am surprised that the statistics table doesn't function as it's explicitly defined, I can fully understand if it was a custom table name.

The create-table path could be added, but at a certain point this becomes unmanageable

**Comment by sinclairpaul** [comment]
The import succeeds, the redirect fails, you mentioned that originally.

**Comment by nagyrobi** [comment]
Yeah that would need a fix. The redirect for root is also in the config you linked, but it doesn't work.

**Comment by nagyrobi** [comment]
Not stale, issue still persists.

**Comment by nagyrobi** [comment]
Bump

**Comment by nagyrobi** [comment]
still an issue

**Comment by sinclairpaul** [comment]
The only real "fix" here would be to remove ingress support and expose the addon directly (the app really doesn't like running from a subfolder), if that will be done is a different question.
