### ISSUE TITLE
Date not in human readable format

### ISSUE THREAD

**Issue by zekje** [hassio-addons/addon-sqlite-web#270]
# Problem/Motivation

colluns  created_ts | start_ts | last_reset_ts   are showing date/time in long format (timestamp ) , before it was in human readable

## Actual/ Expected behavior

ie: i show 1660147210.425684 , on ancien version i show 10-08-2022 18:00:10

how to have the other format ?

**Comment by frenck** [comment]
This is not an add-on related question or issue.

Your question is about the data stored by Home Assistant. All information on the fields and their format can be found on the Home Assistant data portal:

<https://data.home-assistant.io>

../Frenck
