### ISSUE TITLE
SImple query results in black screen and error in log

### ISSUE THREAD

**Issue by MarcoGos** [hassio-addons/addon-sqlite-web#280]
# Problem/Motivation

A simple query like:

SELECT * FROM "statistics_meta"
where has_mean = 1

results in version 3.10 in a black screen and the following error in the log:

Logger: homeassistant.components.http.security_filter
Source: components/http/security_filter.py:66

Filtered a request with unsafe byte query string: /api/hassio_ingress/h2S6ovs3DW_effsVJo3bnlUXkRUuZm2er0UHiAAiios/statistics_meta/query/?ordering=&export_ordering=&sql=SELECT+*+FROM+%22statistics_meta%22%0D%0Awhere+has_mean+%3D+1

## Expected behavior

Expected a query result like in version 3.09

## Actual behavior

Black screen and error in log

## Steps to reproduce

Execute next query:

SELECT * FROM "statistics_meta"
where has_mean = 1

## Proposed changes

If a newline is used in the query the error occurs. Removing the newline solves the problem. In version 3.09 a newline wasn't a problem. Maybe filtering out the newlines before executing the query solves this.

**Comment by mikeynp** [comment]
+1 same here. Different query but same result, server seems to return an HTTP 400 Bad Request.

**Comment by yanglu2021** [comment]
+1 same here. I have some big queries. If I removed the newline, it becomes impossible to read. This is a pain. Please fix ASAP.

**Comment by bassduh** [comment]
I think it is not stale, but needs some love and attention from one of the owners.

**Comment by Santanachia** [comment]
I know it doesn't solve the problem, but write the query in one line
