### ISSUE TITLE
Not starting.

### ISSUE THREAD

**Issue by JohanKrab** [hassio-addons/addon-sqlite-web#306]
After installation sqlite will not start (takes a long time).
Remove-reinstall didn´t help.
Versions:
 Core 2024.1.4
Supervisor 2024.03.1
Operating System 11.5
Frontend 20240104.0

**Comment by frenck** [comment]
Anything in the logs?

**Comment by amordicus** [comment]
Hi,
I have the same problem. From the log file it seems to be started, but the start button is still in a "start" state and the open "OPEN WEB UI" is not displayed.

Nothing in the home-assistant.log file.
Here is what I find in the add-on log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: SQLite Web
 Explore your SQLite database
-----------------------------------------------------------
 Add-on version: 4.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.4.4
 Home Assistant Supervisor: 2024.04.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-sqlite-web: starting
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-sqlite-web successfully started
s6-rc: info: service sqlite-web: starting
s6-rc: info: service sqlite-web successfully started
s6-rc: info: service init-nginx successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[21:45:09] INFO: Starting SQLite Web...
s6-rc: info: service legacy-services successfully started
 * Serving Flask app 'sqlite_web.sqlite_web'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8080
Press CTRL+C to quit
[21:45:10] INFO: Starting NGINX...

If I select the "show in sidebar" and click the "SQLile web" in side bar, I get the message "The add-on is not running. Do you want to start it now"

**Comment by tjorim** [comment]
There are no errors, it's running fine.
Please perform a full host reboot (not a home assistant restart) and check again.

There might be a problem with the supervisor that I recommend checking their issue tracker for.

**Comment by frenck** [comment]
This is an issue with Home Assistant. Please report it with them. A full reboot of your system can solve it.

**Comment by agners** [comment]
@amordicus @tjorim if you encounter the problem again, please report to https://github.com/home-assistant/supervisor/. Also share the Supervisor logs when this happens. Thanks!

**Comment by amordicus** [comment]
Thanks everyone.
