### ISSUE TITLE
Feature request: Support for ingress

### ISSUE THREAD

**Issue by ralphhughes** [hassio-addons/addon-sqlite-web#35]
# Problem/Motivation

I run hass.io behind a reverse proxy on another server. This means it's a pain to have to open multiple ports and write forwarding rules for every addon that needs its own port. 

## Expected behavior

Clicking on "Open web UI" would open the addon

## Actual behavior

Connection timeout due to the addon trying to open port 6210.

## Steps to reproduce

You'd probably have to set up a reverse proxy with nginx or similar and access home assistant through that. Alternatively, blocking port 6210 via firewall would simulate the reverse proxy behaviour.

## Proposed changes

Implement support for home assistant ingress in the same way as the "Configurator addon" and a handful of other addons have done. There is some minimal documentation of ingress here:
https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/
https://developers.home-assistant.io/docs/en/next/hassio_addon_presentation.html#ingress

Thanks for the great addon by the way :-)

<blockquote><img src="https://www.home-assistant.io/images/blog/2019-04-hassio-ingress/blogpost.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/">Introducing Hass.io Ingress</a></strong></div><div>Ingress allows Hass.io add-ons to seamlessly integrate their user interface with Home Assistant</div></blockquote>
<blockquote><img src="https://developers.home-assistant.io/img/default-social.png" width="48" align="right"><div><strong><a href="https://developers.home-assistant.io/index.html">Presenting your add-on · Home Assistant dev docs</a></strong></div><div><p>If you decide to share your add-on to the public, paying attention to details is recommended. Of course, your add-on should have a proper name and description, but Hass.io also gives you some other tools to present your add-on even nicer.</p>
</div></blockquote>

**Comment by ralphhughes** [comment]
Issue open for 2 months without a reply and then marked as stale by a bot? Is this addon unmaintained and abandoned then?

**Comment by frenck** [comment]
No, is an add-on is deprecated it would be marked as such. Just because your feature isn't implemented directly, doesn't mean things are abandoned or unmaintained.

Feel free to implement it and open a PR.

**Comment by ralphhughes** [comment]
Thanks for the reply, I'll add it to the bottom of my todo list but it's unlikely it'll get started anytime soon.

**Comment by frenck** [comment]
Ingress has been added to the dev version and will be part of the next release.
