### ISSUE TITLE
FATAL: The configgured certfile is not found

### ISSUE THREAD

**Issue by Erdccc** [hassio-addons/addon-sqlite-web#5]
# Problem/Motivation
just installed HASS.IO 0.81.6 and 0.2.0 SQLite and I get that error
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by ludeeus** [comment]
set `ssl: false` in the addon config.

**Comment by Erdccc** [comment]
Thanks ludeeus, That did the trick
