### ISSUE TITLE
Unable to configure an in-memory SQLite DB path 

### ISSUE THREAD

**Issue by GaryOkie** [hassio-addons/addon-sqlite-web#68]
# Problem/Motivation
> Unable to determine database path syntax for sqlite-web configuration to accept an in-memory SQLite database.

## Expected behavior

> Sqlite-web should be able to accept a database path of **':memory:'**.   For more information on this option, please see [SQLite In-memory database](https://www.sqlite.org/inmemorydb.html) documentation.

## Actual behavior

> **FATAL: The configured database file is not found**

  ```
Add-on: SQLite Web
 Explore your SQLite database
-----------------------------------------------------------
 Add-on version: 2.2.0
 You are running the latest version of this add-on.
 System: HassOS 3.11  (armv7 / raspberrypi4)
 Home Assistant Core: 0.106.5
 Home Assistant Supervisor: 207
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] sqlite-web.sh: executing... 
[10:13:15] FATAL: The configured database file is not found
[cont-init.d] sqlite-web.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

## Steps to reproduce

> _configuration.yaml_
```
recorder:
  db_url: 'sqlite:///:memory:'
```

>_sqlite-web config:_
```
database_path: ':memory:'
read_only: true
datasette: false
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
```
Note:  I also tried database_paths of: 'file::memory:', '/:memory:"', '//:memory:', '///:memory:', and 'sqlite:///:memory:' .   There may still be a syntax that will work without code changes, but I haven't found it yet.     
## Proposed changes

>  Update help to document the syntax for defining an in-memory database and/or update the code to accept ':memory:' as a valid db path.

**Comment by GaryOkie** [comment]
Just found where in the code this is failing.    In /sqlite-web/rootfs/etc/cont-init.d/**sqlite-web.sh**  the following statements:
```
# Check if database file exist
if ! bashio::fs.file_exists "/config/$(bashio::config 'database_path')"; then
    bashio::exit.nok 'The configured database file is not found'
fi
```
So instead of using the SQLite API to determine if the DB exists, the code is using the bash function library to determine if the file exists, and clearly ":memory:" would not exist s a file.   I can try to create a fake ":memory:" actual file to see if this would be a workaround.   But the best solution would be test for ":memory:" and skip the "bashio.fs.file_exists" test.

**Comment by sinclairpaul** [comment]
Even if the software that the addon wraps supported it (which I don't believe it does), the memory from the HA container where your DB is located, is not shared with this container.

**Comment by GaryOkie** [comment]
ok, created an empty file "_:memory:_" and this satisfied the if file exists test so the sqlite-web app starts up as expected.   However, it appears that the app has opened its own **private instance** of an in-memory database.   This is likely due to it not running in the same docker as Home Assistant.

This sounds like it isn't going to be worth fixing and we just drop it saying this app can't support in-memory databases.   I'll leave this open for the code maintainers to comment if they see it differently.

EDIT:  @sinclairpaul just replied as I was typing this, and we agree.
