### ISSUE TITLE
The example embedding configuration in the README doesn't work due to the dash in sqlite-web

### ISSUE THREAD

**Issue by chetcuti** [hassio-addons/addon-sqlite-web#8]
I was going to submit a PR to quickly fix this, but your contributing guidelines said to first discuss the issue with the repo owner, so I've submitted this issue instead.

# Problem/Motivation

The example embedding configuration in the README doesn't work due to the dash in `sqlite-web`.

Configuration from README:

```
panel_iframe:
  sqlite-web:
    title: SQLite Web
    icon: mdi:database
    url: https://address.to.your.hass.io:6210
```

## Expected behavior

The SQLite Web add-on will load during starting.

## Actual behavior

In addition to the below errors being logged, the SQLite Web add-on doesn't load, and the invalid configuration also seems to break other parts of the HA UI (such as other panel_iframe entries not loading).

```
2019-01-01 09:51:21 ERROR (MainThread) [homeassistant.config] Invalid config for [panel_iframe]: [sqlite-web] is an invalid option for [panel_iframe]. Check: panel_iframe->panel_iframe->sqlite-web. (See /config/configuration.yaml, line 435). Please check the docs at https://home-assistant.io/components/panel_iframe/

2019-01-01 09:51:21 ERROR (MainThread) [homeassistant.setup] Setup failed for panel_iframe: Invalid config.
```

## Steps to reproduce

Use `sqlite-web` under `panel_iframe` in configuration.yaml.

## Proposed changes

Change `sqlite-web` to `sqlite_web` in the README.

**Comment by ludeeus** [comment]
That is mostly in there so you don't "waste" time on adding/changing things that will not be merged :)
Changes to documentation and/or fixes will (usually) always be accepted.
Please open the PR you wanted to correct this.
