### ISSUE TITLE
Can not access database in a folder paret to "config"

### ISSUE THREAD

**Issue by JeeCee1** [hassio-addons/addon-sqlite-web#81]
# Problem/Motivation

In my use case this add-on is not functioning

## Expected behavior
A working add-on; able to locate my database file.

## Actual behavior
"database can not be found"

## Steps to reproduce
Have a database file in a parent folder of "config".

## Proposed changes
According to [this topic](https://community.home-assistant.io/t/full-snapshots-missing-loads-of-files/200775), creating snapshots is incomplete when the database is in its default location.

I have moved my DB to ~/share/some folder/database, which this add-on can not reach (addon-sqlite-web/sqlite-web/rootfs/etc/cont-init.d/sqlite-web.sh)

**Comment by frenck** [comment]
> Explore your Home-Assistant database from your web browser!

The Home Assistant database is located in that folder.

Sorry, cannot help your use case.

**Comment by JeeCee1** [comment]
Hi Frenck, thanks for the quick reply!

On a default installation it is indeed in that folder, but users can move the database.
Are there technical objections to not allowing for this?

**Comment by frenck** [comment]
There is no folder higher up that tree... if you go one folder up, you'll end up in the container of the add-on itself.

**Comment by JeeCee1** [comment]
Maybe not for this add-on (are they sandboxed? I’m still new to HASS).

I have moved my DB to “root”/share (~/share) and pointed the recorder to this path, so this folder is accessible at least to HA core itself.


On 7. Jul 2020, at 01:46, Franck Nijhof <notifications@github.com> wrote:

﻿

There is no folder higher up that tree... if you go one folder up, you'll end up in the container of the add-on itself.

**Comment by frenck** [comment]
Everything in supervisor based installations is sandboxed, using Docker containers.
`/share/` could be accessed, but it needs a bit of logic and adjustments I guess. Re-opening and will take a look.

**Comment by juzel69** [comment]
I moved the database to /share/disk /... I can connect an external disc to this directory. If the database is left in config, the SD card will soon be defective because of the high number of write accesses.
