### ISSUE TITLE
Local Time not being returned in query

### ISSUE THREAD

**Issue by kaizersoje** [hassio-addons/addon-sqlite-web#96]
# Problem/Motivation

> (Why the issue was filed)

Query not returning the local datetime even after using the datetime modifier "localtime". 

```
SELECT datetime('now','localtime') time
union all
SELECT datetime('now')
```
## Expected behavior

> (What you expected to happen)
The first row in the query should return time in local time zone and not UTC.

## Actual behavior

> (What actually happened)
The query returns both rows in UTC and not local time.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
It's inherited from the OS.  Although you haven't posted the details I assume this is a HassOS install?

**Comment by kaizersoje** [comment]
Yes, that is correct. I am pretty sure it was working fine in v 0.116.x

**Comment by sinclairpaul** [comment]
The Homeassistant version has nothing to do with the addon.  HassOS runs on UTC from my understanding, you would need to log any request to change it with the OS repo. 

There isn't anything that can be done from an addon perspective, on my supervised install the localtime reports fine.
