### ISSUE TITLE
Improvement: history or favorites

### ISSUE THREAD

**Issue by z4rn0x** [hassio-addons/addon-sqlite-web#98]
Hello! Thank you for what you did  with this addon, I'm using it quite often on my HA. I'd like to submit an idea that could be an improvement for this add-on.
I'm using the same requests on a regular basis, so would it be possible either to keep an history of the requests recently used (like the 10 last ones? or even better, to save some favorite requests? I know nothing at programming, so unfortunately I can't submit anything on Github.
Hope you'll like the idea!

**Comment by frenck** [comment]
Add-ons wrap existing applications. In this case: SQLite Web.

We don't build the application itself. If you have a feature suggestion for the application running inside this add-on, please head over to the upstream project:

<https://github.com/coleifer/sqlite-web>

Thanks 👍
